"""Ontology coverage report: generated from a built canonical.db so the
numbers can't drift from what actually ships.

    uv run mnemosyne-coverage --db /path/to/canonical.db --out docs/ontology-coverage.md
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path

from mnemosyne.config import canonical_db_path


def _rows(conn: sqlite3.Connection, sql: str, params: tuple = ()) -> list[tuple]:
    return conn.execute(sql, params).fetchall()


def generate_coverage_markdown(db_path: Path) -> str:
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        meta = dict(_rows(conn, "SELECT key, value FROM schema_meta"))
        (entity_count,) = _rows(conn, "SELECT COUNT(*) FROM entities")[0]
        (alias_count,) = _rows(conn, "SELECT COUNT(*) FROM aliases")[0]
        (rel_count,) = _rows(conn, "SELECT COUNT(*) FROM relationships")[0]
        (assertion_count,) = _rows(conn, "SELECT COUNT(*) FROM assertions")[0]
        by_type = _rows(
            conn,
            "SELECT entity_type, COUNT(*) FROM entities GROUP BY entity_type ORDER BY 2 DESC",
        )
        rels_by_type = _rows(
            conn,
            "SELECT rel_type, COUNT(*) FROM relationships GROUP BY rel_type ORDER BY 2 DESC",
        )
        most_aliased = _rows(
            conn,
            """SELECT e.name, e.entity_type, COUNT(a.id) AS n
               FROM entities e JOIN aliases a ON a.entity_id = e.id
               GROUP BY e.id ORDER BY n DESC LIMIT 10""",
        )
        imports = {
            key.removeprefix("import:"): json.loads(value)
            for key, value in meta.items()
            if key.startswith("import:")
        }

        lines = [
            "# Ontology Coverage",
            "",
            "> Auto-generated by `mnemosyne-coverage` from the built canonical database.",
            "> Regenerate after any seed or import change — do not edit by hand.",
            "",
            f"- **Built:** {meta.get('seeded_at', 'unknown')}",
            f"- **Entities:** {entity_count:,}",
            f"- **Aliases:** {alias_count:,} "
            f"({alias_count / entity_count:.1f} per entity on average)"
            if entity_count
            else "- **Aliases:** 0",
            f"- **Relationships:** {rel_count:,}",
            f"- **Assertion log entries:** {assertion_count:,} "
            "(full append-only history, seed provenance included)",
            "",
            "## Entities by type",
            "",
            "| Entity type | Count |",
            "|---|---:|",
            *[f"| {t} | {n:,} |" for t, n in by_type],
            "",
            "## Relationships by type",
            "",
            "| Relationship | Count |",
            "|---|---:|",
            *[f"| {t} | {n:,} |" for t, n in rels_by_type],
            "",
            "## Sources",
            "",
        ]
        for name, stats in sorted(imports.items()):
            source = stats.get("source") or "curated base seed"
            lines.append(
                f"- **{name}** ({source}): {stats.get('entities', 0):,} entities, "
                f"{stats.get('aliases', 0):,} aliases, "
                f"{stats.get('relationships', 0):,} relationships"
            )
            skipped_dup = stats.get("skipped_duplicates", 0)
            skipped_rel = stats.get("skipped_invalid_rels", 0)
            if skipped_dup or skipped_rel:
                lines.append(
                    f"  - deduplicated {skipped_dup:,} name collisions "
                    f"(aliases merged onto existing entities); "
                    f"skipped {skipped_rel:,} relationships failing ontology "
                    f"constraints or referencing out-of-scope entities"
                )
        lines += [
            "",
            "## Most-aliased entities",
            "",
            "| Entity | Type | Aliases |",
            "|---|---|---:|",
            *[f"| {name} | {etype} | {n} |" for name, etype, n in most_aliased],
            "",
            "## Method and scope",
            "",
            "Coverage is **comprehensive by domain, not universal**: the Wikidata import",
            "pulls scoped slices (software/technology companies, programming languages,",
            "notable software, major platforms) with a per-slice notability floor",
            "(Wikipedia sitelink count), rather than attempting a universal ontology.",
            "Wikidata content is CC0; every imported entity records its QID in",
            "`attributes.wikidata_qid` and its import file in seed provenance, so each",
            "canonical fact traces to a public source.",
            "",
            "Known gaps: people, locations, events, and non-tech industries are not yet",
            'imported; descriptions-as-aliases (e.g. "the lakehouse vendor") exist only',
            "in the curated base seed; slice membership uses direct `P31` typing, so",
            "entities typed only via subclasses are missed. The overlay tier's",
            "propose-and-review flow is the intended path for filling gaps from real",
            "usage.",
            "",
        ]
        return "\n".join(lines)
    finally:
        conn.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the ontology coverage report.")
    parser.add_argument("--db", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None, help="Write here (default: stdout)")
    args = parser.parse_args(argv)
    db_path = args.db or canonical_db_path()
    if not db_path.exists():
        print(f"No canonical DB at {db_path} — run mnemosyne-seed first.", file=sys.stderr)
        return 1
    markdown = generate_coverage_markdown(db_path)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(markdown)
        print(f"Wrote {args.out}")
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    sys.exit(main())
